const listAllPeople = [
  {
    color: 'transparent',
    id: 0,
    active: false,
    name: 'Agus_Brolese',
    rama: 'Emaùs',
  },
  { color: 'transparent', id: 1, active: false, name: 'Alex', rama: 'Effeta' },
  {
    color: 'transparent',
    id: 2,
    active: false,
    name: 'Andrea',
    rama: 'Camino',
  },
  { color: 'transparent', id: 3, active: false, name: 'Belen_R', rama: 'Ruah' },
  { color: 'transparent', id: 4, active: false, name: 'Belen_Z', rama: 'Ruah' },
  {
    color: 'transparent',
    id: 5,
    active: false,
    name: 'Belu_Blume',
    rama: 'Emaùs',
  },
  { color: 'transparent', id: 6, active: false, name: 'Bianca', rama: 'Emaùs' },
  { color: 'transparent', id: 7, active: false, name: 'Brian', rama: 'Effeta' },
  {
    color: 'transparent',
    id: 8,
    active: false,
    name: 'Brisa_Alemi',
    rama: 'Emaùs',
  },
  { color: 'transparent', id: 9, active: false, name: 'Camy', rama: 'Ruah' },
  {
    color: 'transparent',
    id: 10,
    active: false,
    name: 'Cande_Diaz',
    rama: 'Emaùs',
  },
  {
    color: 'transparent',
    id: 11,
    active: false,
    name: 'Carli',
    rama: 'Effeta',
  },
  {
    color: 'transparent',
    id: 12,
    active: false,
    name: 'Carmen',
    rama: 'Camino',
  },
  {
    color: 'transparent',
    id: 13,
    active: false,
    name: 'Checha',
    rama: 'Camino',
  },
  { color: 'transparent', id: 14, active: false, name: 'Coni', rama: 'Emaùs' },
  { color: 'transparent', id: 15, active: false, name: 'Dai', rama: 'Effeta' },
  { color: 'transparent', id: 16, active: false, name: 'Delfy', rama: 'Ruah' },
  { color: 'transparent', id: 17, active: false, name: 'Ema', rama: 'Ruah' },
  { color: 'transparent', id: 18, active: false, name: 'Erika', rama: 'Ruah' },
  {
    color: 'transparent',
    id: 19,
    active: false,
    name: 'Estelita',
    rama: 'Camino',
  },
  { color: 'transparent', id: 20, active: false, name: 'Facha', rama: 'Ruah' },
  { color: 'transparent', id: 21, active: false, name: 'Fede', rama: 'Effeta' },
  { color: 'transparent', id: 22, active: false, name: 'Fer', rama: 'Effeta' },
  { color: 'transparent', id: 23, active: false, name: 'Flor', rama: 'Effeta' },
  { color: 'transparent', id: 24, active: false, name: 'Fran', rama: 'Ruah' },
  {
    color: 'transparent',
    id: 25,
    active: false,
    name: 'Fran_Elal',
    rama: 'Effeta',
  },
  {
    color: 'transparent',
    id: 26,
    active: false,
    name: 'Georgi',
    rama: 'Effeta',
  },
  { color: 'transparent', id: 27, active: false, name: 'Guada', rama: 'Ruah' },
  {
    color: 'transparent',
    id: 28,
    active: false,
    name: 'Gustavo',
    rama: 'Effeta',
  },
  { color: 'transparent', id: 29, active: false, name: 'Ivo', rama: 'Ruah' },
  {
    color: 'transparent',
    id: 30,
    active: false,
    name: 'Jesus',
    rama: 'Effeta',
  },
  {
    color: 'transparent',
    id: 31,
    active: false,
    name: 'Juan_Cruz',
    rama: 'Ruah',
  },
  { color: 'transparent', id: 32, active: false, name: 'Justi', rama: 'Emaùs' },
  {
    color: 'transparent',
    id: 33,
    active: false,
    name: 'Lila_Gomez',
    rama: 'Emaùs',
  },
  {
    color: 'transparent',
    id: 34,
    active: false,
    name: 'Lili_M',
    rama: 'Camino',
  },
  {
    color: 'transparent',
    id: 35,
    active: false,
    name: 'Lili_T',
    rama: 'Camino',
  },
  {
    color: 'transparent',
    id: 36,
    active: false,
    name: 'Lucia',
    rama: 'Camino',
  },
  {
    color: 'transparent',
    id: 37,
    active: false,
    name: 'M_Emilia',
    rama: 'Ruah',
  },
  {
    color: 'transparent',
    id: 38,
    active: false,
    name: 'Maichu',
    rama: 'Effeta',
  },
  {
    color: 'transparent',
    id: 39,
    active: false,
    name: 'Mailin_Brolese',
    rama: 'Emaùs',
  },
  {
    color: 'transparent',
    id: 40,
    active: false,
    name: 'Maite',
    rama: 'Effeta',
  },
  { color: 'transparent', id: 41, active: false, name: 'Marcos', rama: 'Ruah' },
  {
    color: 'transparent',
    id: 42,
    active: false,
    name: 'Marcos',
    rama: 'Effeta',
  },
  { color: 'transparent', id: 43, active: false, name: 'Mari_G', rama: 'Ruah' },
  {
    color: 'transparent',
    id: 44,
    active: false,
    name: 'Marta',
    rama: 'Camino',
  },
  {
    color: 'transparent',
    id: 45,
    active: false,
    name: 'Martina',
    rama: 'Ruah',
  },
  {
    color: 'transparent',
    id: 46,
    active: false,
    name: 'Mati_Vitteli',
    rama: 'Emaùs',
  },
  {
    color: 'transparent',
    id: 47,
    active: false,
    name: 'Maty_Blume',
    rama: 'Ruah',
  },
  { color: 'transparent', id: 48, active: false, name: 'Mauro', rama: 'Ruah' },
  {
    color: 'transparent',
    id: 49,
    active: false,
    name: 'Maxi_G',
    rama: 'Effeta',
  },
  { color: 'transparent', id: 50, active: false, name: 'Maxy', rama: 'Ruah' },
  {
    color: 'transparent',
    id: 51,
    active: false,
    name: 'Micaela_Chavez',
    rama: 'Emaùs',
  },
  {
    color: 'transparent',
    id: 52,
    active: false,
    name: 'Mili_zaneti',
    rama: 'Emaùs',
  },
  {
    color: 'transparent',
    id: 53,
    active: false,
    name: 'Mli_Pera',
    rama: 'Emaùs',
  },
  { color: 'transparent', id: 54, active: false, name: 'Moni', rama: 'Camino' },
  {
    color: 'transparent',
    id: 55,
    active: false,
    name: 'Monica',
    rama: 'Emaùs',
  },
  {
    color: 'transparent',
    id: 56,
    active: false,
    name: 'Nico_F',
    rama: 'Effeta',
  },
  {
    color: 'transparent',
    id: 57,
    active: false,
    name: 'Nico_M',
    rama: 'Effeta',
  },
  { color: 'transparent', id: 58, active: false, name: 'Nidi', rama: 'Effeta' },
  {
    color: 'transparent',
    id: 59,
    active: false,
    name: 'Pasquini',
    rama: 'Effeta',
  },
  {
    color: 'transparent',
    id: 60,
    active: false,
    name: 'Patri',
    rama: 'Camino',
  },
  {
    color: 'transparent',
    id: 61,
    active: false,
    name: 'Raul_Landini',
    rama: 'Emaùs',
  },
  {
    color: 'transparent',
    id: 62,
    active: false,
    name: 'Raul_yusa',
    rama: 'Pescadores',
  },
  { color: 'transparent', id: 63, active: false, name: 'Sofy', rama: 'Ruah' },
  { color: 'transparent', id: 64, active: false, name: 'Susi', rama: 'Camino' },
  { color: 'transparent', id: 65, active: false, name: 'Taty', rama: 'Ruah' },
  { color: 'transparent', id: 66, active: false, name: 'Tita', rama: 'Camino' },
  {
    color: 'transparent',
    id: 67,
    active: false,
    name: 'Tomas_Fries',
    rama: 'Emaùs',
  },
  { color: 'transparent', id: 68, active: false, name: 'Tomy', rama: 'Ruah' },
  { color: 'transparent', id: 69, active: false, name: 'Vale', rama: 'Effeta' },
  { color: 'transparent', id: 70, active: false, name: 'Vero', rama: 'Effeta' },
  {
    color: 'transparent',
    id: 71,
    active: false,
    name: 'Vicky',
    rama: 'Effeta',
  },
  {
    color: 'transparent',
    id: 72,
    active: false,
    name: 'Xiomara',
    rama: 'Emaùs',
  },
]
